entity_movie.entity_movie.*:
  type: config_entity
  label: Entity movie
  mapping:
    id:
      type: string
      label: ID
    name:
      type: label
      label: name
    award:
      type: label
      label: award
    date:
      type: number
      label: date 
    uuid:
      type: string
    description:
      type: string
