<?php

use Drupal\Core\Url;

/**
 * Implements hook_entity_view().
 *
 */
function product_page_entity_view(array &$build, \Drupal\Core\Entity\EntityInterface $entity, \Drupal\Core\Entity\Display\EntityViewDisplayInterface $display, $view_mode) {
  
  if(\Drupal::currentUser()->isAuthenticated()){
    if ($entity->getEntityType()->id() == 'node' && $entity->bundle() == 'products' && $view_mode == 'full') {

      $value = $entity->id();
  
      // Build the URL for the controller action with the query parameter.
      $url = Url::fromRoute('product_page.thnkuPage', ['node_id' => $value])->toString();
      // dd($url);
  
      $route = '<div><a href="' . $url. '" class="btn-style">Buy Now</a></div';
  
  
  
      $build['product_cart'] = [
        '#type' => 'button',
        '#name' => 'cart_button',
        '#value' => t('Add To Cart'),
        '#weight' => 1000,
        '#prefix' => '</br>',
        '#attributes' => [
          'class' => ['button', 'button--primary', 'cart-btn'],
          'id' => 'press',
        ],
  
      ];
      $build['message'] = [
        '#type' => 'markup',
        '#markup' => t('<div id="message-id"></div>'),
        '#weight' => 1001,
  
      ];
  
      $build['buy_now'] = [
        '#type' => 'markup',
        '#name' => 'buy',
        '#markup' => t($route),
        '#weight' => 1002,
        '#prefix' => '</br>',
        '#attributes' => [
          'id' => 'buy_now',
        ]
      ];
    }
  }
  
}

/**
 * Implements hook_preprocess_node().
 */
function product_page_preprocess_node(&$variables)
{
  $node = $variables['node'];
  if ($node->getType() == 'products') {
    $variables['#attached']['library'][] = 'product_page/product_page.click';
  }
}
