<?php

  function blocks_module_user_login($account) {
    // Check if the user has the necessary permission to redirect.
    if (\Drupal::currentUser()->hasPermission('access content')) {
      // Redirect the user to a different page after login.
      $response = new \Symfony\Component\HttpFoundation\RedirectResponse('/custom-welcome-page');
      $response->send();
    }
  }
  // use Drupal\Core\Form\FormStateInterface;
  // use Drupal\Core\Url;

  // /**
  //  * Implements hook_form_FORM_ID_alter().
  //  */
  // function blocks_module_form_user_login_form_alter(&$form, FormStateInterface $form_state, $form_id) {
  //   $form['#submit'][] = 'blocks_module_user_login_form_submit';
  // }
  
  // /**
  //  * Custom submit handler for the login form.
  //  */
  // function blocks_module_user_login_form_submit($form, FormStateInterface $form_state) {
  //   $url = Url::fromRoute('blocks_module.welcomePage');
  //   $form_state->setRedirectUrl($url);
  // }

?>