<?php

use Drupal\Core\Form\FormStateInterface;

/**
 * @file
 * Primary module hooks for login_alter module.
 */

/**
 * Implements hook_form_alter().
 */
function login_with_otp_form_alter(&$form, FormStateInterface $form_state, $form_id , $uid = NULL) {
  if($form_id == 'user_login_form') {
    dd($form);
    unset($form['name']);
    unset($form['pass']);
    unset($form['#validate']);
    unset($form['#submit'][0]);
    $form['fullname'] = [
      '#type' => 'textfield',
      '#title' => t('Full Name'),
      '#required' => TRUE,
    ];
    $form['email'] = [
      '#type' => 'email',
      '#title' => t('Email'),
      '#required' => TRUE,
    ];
    $form['password'] = [
      '#type' => 'password',
      '#title' => t('Password'),
      '#required' => TRUE,
    ];
    $form['#validate'][] = 'login_with_otp_user_login_form_submit';
  }
}

/**
 * Custom Submit handler for the user login form alter.
 *
 * @param mixed $form
 *   Holds the data associated with the form.
 * @param FormStateInterface $form_state
 *   Holds the current form state.
 *
 * @return Null|String
 *   Logs in user if succesfull else throws error
 */
function login_with_otp_user_login_form_submit(&$form, FormStateInterface $form_state) {
  $email = $form_state->getValue('email');
  $password = $form_state->getValue('password');
  $full_name = $form_state->getValue('fullname');
  $users_by_name = \Drupal::entityTypeManager()->getStorage('user')->loadByProperties([
    'field_full_name' => $full_name,
  ]);
  $users_by_email = \Drupal::entityTypeManager()->getStorage('user')->loadByProperties([
    'mail' => $email,
  ]);
  $users = $users_by_email + $users_by_name;
  if($users) {
    $user = reset($users);
    $is_valid = \Drupal::service('password')->check($password, $user->getPassword());
    if($is_valid) {
      $otp = rand(1000,9999);
      $session = \Drupal::requestStack()->getCurrentRequest()->getSession();
       $session->set('login_alter_otp', $otp);
      // login_with_otp_send_otp($email, $otp);
      $form_state->setRedirect('login_with_otp.validate_otp', ['uid' => $user->id()]);
    } else {
      $form_state->setErrorByName('password', t('Invalid email or password'));
    }
  }
}

function login_with_otp_send_otp($email,$otp) {
  $message = "OTP for Login Request is :\n";
  $message .=$otp;
  $params['message'] = $message;
  $admin_email = \Drupal::config('system.site')->get('mail');
  $mailManager = \Drupal::service('plugin.manager.mail');
  $module = 'login_with_otp';
  $key = 'user_login_otp';
  $to = $email;
  $langcode = \Drupal::currentUser()->getPreferredLangcode();
  $send = TRUE;
  $result = $mailManager->mail($module, $key, $to, $langcode, $params, NULL, $send);
}

function login_with_otp_mail($key, &$message , $params) {
  $options = [
    'langcode' => $message['langcode'],
  ];
  switch ($key) {
    case 'user_login_otp':
      $message['from'] = \Drupal::config('system.site')->get('mail');
      $message['subject'] = t('OTP for user login');
      $message['body'][] = $params['message'];
      break;
  }
}


